# Generated by Django 3.1 on 2021-11-13 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomapp', '0008_contactform_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='phone',
            field=models.PositiveIntegerField(max_length=10),
        ),
    ]
